src/app.py
from flask import Flask
from views.home_view import home_blueprint
from views.animals_view import animals_blueprint
from views.contact_us_view import contact_us_blueprint

app = Flask(__name__)

app.register_blueprint(home_blueprint)
app.register_blueprint(animals_blueprint)
app.register_blueprint(contact_us_blueprint)

src/views/animals_view.py
from flask import Blueprint, render_template

animals_blueprint = Blueprint("animals_view", __name__)

@animals_blueprint.route("/animals")
def animals():
    return render_template("animals.html")

src/views/contact_us_view.py
from flask import Blueprint, render_template

contact_us_blueprint = Blueprint("contact_us_view", __name__)

@contact_us_blueprint.route("/contact-us")
def contact_us():
    return render_template("contact_us.html")

src/views/home_view.py
from flask import Blueprint, render_template

home_blueprint = Blueprint("home_view", __name__)

@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    return render_template("home.html")

src/templates/animals.html
{% extends "layout.html" %}

{% block title %}
Animals
{% endblock title %}

{% block nav %}
<a href="{{ url_for('home_view.home') }}">Home</a>
<a href="{{ url_for('animals_view.animals') }}" class="active">Animals</a>
<a href="{{ url_for('contact_us_view.contact_us') }}">Contact Us</a>
{% endblock nav %}

{% block content %}
<p class="mainPar">Here are some of our animals:</p>
<div class="animalsContainer">
    <img src="{{ url_for('static', filename='images/pet1.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet2.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet3.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet4.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet5.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet6.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet7.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet8.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet9.jpg') }}">
    <img src="{{ url_for('static', filename='images/pet10.jpg') }}">
</div>
{% endblock content %}

src/templates/contact_us.html
{% extends "layout.html" %}

{% block title %}
Contact Us
{% endblock title %}

{% block nav %}      
    <a href="{{ url_for('home_view.home') }}">Home</a>
    <a href="{{ url_for('animals_view.animals') }}">Animals</a>
    <a href="{{ url_for('contact_us_view.contact_us') }}" class="active">Contact Us</a>
{% endblock nav %}

{% block content %}
<div class="form-container">
    <form>
        <div>
            <label for="name_box">Name:</label>
        </div>
        <div>
            <input class="form-control" type="text" name="full_name" id="name_box" required minlength="2" maxlength="30">
        </div>
        <div>
            <label for="message_box">Message:</label>
        </div>
        <div>
            <textarea class="form-control" name="message" id="message_box" required minlength="5" maxlength="1000"></textarea>
        </div>
        <div></div>
        <div>
            <button class="btn btn-primary">Send</button>
        </div>
    </form>
</div>
{% endblock content %}

src/templates/home.html
{% extends "layout.html" %}

{% block title %}
Home
{% endblock title %}

{% block nav %}      
    <a href="{{ url_for('home_view.home') }}" class="active">Home</a>
    <a href="{{ url_for('animals_view.animals') }}">Animals</a>
    <a href="{{ url_for('contact_us_view.contact_us') }}">Contact Us</a>
{% endblock nav %}

{% block content %}

    <p class="mainPar">Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic vitae quas rerum maiores, doloremque omnis dolore temporibus voluptatum molestias aut reprehenderit, veritatis blanditiis possimus eligendi optio aspernatur dolorum sapiente exercitationem, deleniti excepturi consequatur iure illum minus? Rerum eligendi perspiciatis laborum obcaecati necessitatibus ipsam voluptate commodi, mollitia reprehenderit. Ullam, soluta accusantium.</p>
    
    <iframe width="560" height="315" src="https://www.youtube.com/embed/Y6cwMDpARao?si=P3CpKsS-hcMsKtja" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

    <div class="layout">

        <header>
            <h1>Animal Store</h1>
        </header>

        <aside>
            {% block nav %}
            {% endblock nav %}
        </aside>

        <main>
            {% block content %}
            {% endblock content %}
        </main>

        <footer>
            <div>
                All Rights Reserved ©️
            </div>
        </footer>

    </div>
    
</body>
</html>